### ISSUE TITLE
Add instructions

### ISSUE THREAD

**Issue by tibequadorian** [joshbarrass/TerrariaServerWrapper#1]
Hey, would you mind adding instructions on how to compile this program? :)
I'm not experienced with go and it took me a while to figure it out

**Comment by joshbarrass** [comment]
[Added.](https://github.com/joshbarrass/TerrariaServerWrapper/blob/master/README.md#compiling) This should be all that is required, but if you need further details please let me know and I will add more.

**Comment by tibequadorian** [comment]
Thank you!
